spring:
  rabbitmq:
    host: 192.168.20.138
  application:
    name: cc-rabbitmq
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.138:3306/cc_article?characterEncoding=UTF8
    username: root
    password: 123456
server:
  port: 8001