#更改该应用的端口号
server:
  port: 9001
#springcloud要求微服务的应用名称必须是-，不能使用_
spring:
  application:
    name: cc-base
  #设置jdbc相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.138:3306/cc_base?characterEncoding=utf-8
    username: root
    password: 123456
  #设置jpa相关配置
  jpa:
    database: mysql
    show-sql: true

